version: "3"
services:
  db:
    image: postgres
    restart: always
    container_name: postgres
    volumes:
      - ./data/postgres/db-data:/var/lib/postgresql/data
      - ./database:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_MULTIPLE_DATABASES=books,test
    ports:
      - 5432:5432
